name: koscom-springboot-aws

on:
  push:
    branches:
      - master # (1)
  workflow_dispatch: # (2) 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest # (3) 수행되는 OS 환경

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4) github에서 프로젝트를 다운받습니다

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # (5) OS에 Java를 설치
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # (6) gradlew 실행권한을 추가
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # (7) gradlew 로 빌드(test & jar파일 생성)를 수행
        shell: bash